monetdb_user: monetdb
monetdb_password: monetdb

monetdb_bin_dir: "{% if monetdb_prefix is defined %}{{ monetdb_prefix }}/bin/{% endif %}"

atraf_config_name: "{{ atraf_subset }}_{{ ansible_play_hosts | length }}x"
atraf_db: "{{ atraf_config_name }}"
atraf_local_config_dir: "gen/{{ atraf_config_name }}"
atraf_remote_config_dir: "{{ atraf_dir }}/{{ atraf_config_name }}"

atraf_force_reload: no

# by default every node but the first has data
atraf_data: True
